using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Reflectonia;
using Reflectonia.Model;

// ReSharper disable once CheckNamespace
namespace Generator;

public class BuilderAliasesGenerator
{
    public BuilderAliasesGenerator(ReflectoniaFactory reflectoniaFactory, IReflectoniaLog log)
    {
        ReflectoniaFactory = reflectoniaFactory;
        Log = log;
    }

    private ReflectoniaFactory ReflectoniaFactory { get; }

    private IReflectoniaLog Log { get; }

    public void Generate(string propsPath, List<Class> classes)
    {
        var directory = Path.GetDirectoryName(propsPath);
        if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
        {
            Directory.CreateDirectory(directory);
        }

        using var file = new StreamWriter(propsPath, append: false, Encoding.UTF8);
        void WriteLine(string text) => file.WriteLine(text);

        WriteLine(@"<Project DefaultTargets=""Build"" xmlns=""http://schemas.microsoft.com/developer/msbuild/2003"">");
        WriteLine("  <!-- <auto-generated /> -->");
        WriteLine("  <ItemGroup>");

        foreach (var (alias, typeName) in BuilderAliasRegistry.GetAliasEntries())
        {
            var includeValue = XmlEscape($"NXUI.HotReload.Nodes.ElementBuilder<{typeName}>");
            WriteLine($"    <Using Include=\"{includeValue}\" Alias=\"{alias}\" />");
        }

        WriteLine("  </ItemGroup>");
        WriteLine("</Project>");
        Log.Info($"Generated {BuilderAliasRegistry.GetAliasEntries().Count()} builder aliases at `{propsPath}`.");
    }

    private static string XmlEscape(string value)
    {
        return value
            .Replace("&", "&amp;")
            .Replace("\"", "&quot;")
            .Replace("'", "&apos;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;");
    }
}
