using System.Diagnostics.CodeAnalysis;

// ReSharper disable once CheckNamespace
namespace Generator;

[SuppressMessage("ReSharper", "InconsistentNaming")]
public static partial class Templates
{
    public static string FileHeaderTemplate = """
// <auto-generated />
#nullable enable
namespace NXUI%Namespace%.Extensions;

#if NXUI_HOTRELOAD
using NXUI.HotReload.Metadata;
using NXUI.HotReload.Nodes;
#endif
""";
}
