using System.Diagnostics.CodeAnalysis;

// ReSharper disable once CheckNamespace
namespace Generator;

[SuppressMessage("ReSharper", "InconsistentNaming")]
public static partial class Templates
{
    public static string ElementRefExtensionsHeader = """
// <auto-generated />
#nullable enable
namespace NXUI.Extensions;

using System;
using NXUI.HotReload.Nodes;

/// <summary>
/// ElementRef helpers for <see cref="%ClassType%"/>.
/// </summary>
public static partial class %ClassName%ElementRefExtensions
{
""";

    public static string ElementRefExtensionsMethod = """

    /// <summary>
    /// Observes the <see cref="%ClassType%.%Name%Property"/> value.
    /// </summary>
    public static IObservable<%ValueTypeSignature%> Observe%Name%%GenericSuffix%(this %ElementRefType% elementRef)%Constraint%
    {
        return elementRef.Observe(%ClassType%.%Name%Property);
    }

""";

    public static string ElementRefExtensionsFooter = """
}
""";
}
