using System.Diagnostics.CodeAnalysis;

// ReSharper disable once CheckNamespace
namespace Generator;

[SuppressMessage("ReSharper", "InconsistentNaming")]
public static partial class Templates
{
    public static string PropertiesHeaderTemplate = """
// <auto-generated />
namespace NXUI;

/// <summary>
/// The minimal avalonia properties.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "RedundantNameQualifier")]
public static partial class Properties
{
""";

    public static string PropertyTemplate = """
    /// <summary>
    /// The <see cref="%ClassType%.%PropertyName%Property"/> property defined in <see cref="%ClassType%"/> class.
    /// </summary>
    public static %PropertyType% %ClassName%%PropertyName% => %ClassType%.%PropertyName%Property;
""";

    public static string PropertiesFooterTemplate = @"}";
}
