using System.Diagnostics.CodeAnalysis;

// ReSharper disable once CheckNamespace
namespace Generator;

[SuppressMessage("ReSharper", "InconsistentNaming")]
public static partial class Templates
{
    public static string FileHeaderTemplate = """
// <auto-generated />
namespace NXUI.Extensions;
""";
}
