using System.Diagnostics.CodeAnalysis;

namespace Generator;

[SuppressMessage("ReSharper", "InconsistentNaming")]
internal static partial class Templates
{
    public static string FileHeaderTemplate = @"// <auto-generated />
namespace MinimalAvalonia.Extensions;";

    public static string ClassExtensionsHeaderTemplate = @"
public static partial class %ClassName%Extensions
{";

    public static string ClassExtensionsFooterTemplate = @"}";
}
